CREATE TABLE Majors
(
  [MajorID] INT IDENTITY NOT NULL,
  [Name] NVARCHAR(50) NOT NULL,
  CONSTRAINT PK_Majors PRIMARY KEY(MajorID)
)

CREATE TABLE Subjects
(
  [SubjectID] INT IDENTITY NOT NULL,
  [SubjectName] NVARCHAR(50) NOT NULL,
  CONSTRAINT PK_Subjects PRIMARY KEY(SubjectID),
)

CREATE TABLE Students
(
  [StudentID] INT IDENTITY NOT NULL,
  [StudentNumber] INT NOT NULL,
  [StudentName] NVARCHAR(50) NOT NULL,
  [MajorID] INT,
  CONSTRAINT PK_Students PRIMARY KEY(StudentID),
  CONSTRAINT FK_MajorID FOREIGN KEY(MajorID) REFERENCES Majors(MajorID)
)

CREATE TABLE Payments
(
  [PaymentID] INT IDENTITY NOT NULL,
  [PaymentDate] DATE NOT NULL,
  [PaymentAmount] REAL NOT NULL,
  [StudentID] INT NOT NULL,
  CONSTRAINT PK_Payments PRIMARY KEY(PaymentID),
  CONSTRAINT FK_StudentID FOREIGN KEY(StudentID) REFERENCES Students(StudentID)
)

CREATE TABLE Agenda
(
  [StudentID] INT NOT NULL,
  [SubjectID] INT NOT NULL,
  CONSTRAINT PK_Agenda PRIMARY KEY(StudentID, SubjectID),
  CONSTRAINT FK_Agenda_StudentID FOREIGN KEY(StudentID) REFERENCES Students(StudentID),
  CONSTRAINT FK_Agenda_SubjectID FOREIGN KEY(SubjectID) REFERENCES Subjects(SubjectID)
)